server:
  port: 8080

spring:
  application:
    name: ApiGateway
  security:
    csrf:
      enabled: false
  # Static resource serving
  webflux:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:*"
              - "https://localhost:*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: false
      httpclient:
        connect-timeout: 30000
        response-timeout: 30s

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890

# Logging
logging:
  level:
    com.example.apigateway: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework.web.cors: DEBUG
    reactor.netty: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Health check - Configure management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  server:
    port: 8080  # Use same port as main application