server:
  port: 8080

spring:
  application:
    name: ApiGateway

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  web:
    cors:
      allowed-origins: "http://localhost:63342,http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

  cloud:
    gateway:
      routes:
        # User Service Routes
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**, /api/users/**
          filters:
            - StripPrefix=0

        # Subscription Service Routes
        - id: subscription-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/subscriptions/**
          filters:
            - StripPrefix=0

        # User-Subscription Service Routes
        - id: user-subscription-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/user-subscriptions/**
          filters:
            - StripPrefix=0

        # Email Service Routes
        - id: email-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/email/**
          filters:
            - StripPrefix=0

      # Global CORS Configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    az.subscription: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
